//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.NarudzbinaProizvod = new HashSet<NarudzbinaProizvod>();
        }
    
        public int ProizvodID { get; set; }
        public string Naziv { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<int> ProdavacID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbinaProizvod> NarudzbinaProizvod { get; set; }
        public virtual Prodavac Prodavac { get; set; }
    }
}
