//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public int KorisnikID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Tip { get; set; }
    
        public virtual Kupac Kupac { get; set; }
        public virtual Prodavac Prodavac { get; set; }
    }
}
