//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupac()
        {
            this.Narudzbina = new HashSet<Narudzbina>();
        }
    
        public int KorisnikID { get; set; }
        public string TipKupca { get; set; }
        public Nullable<int> FizickoLiceID { get; set; }
        public Nullable<int> FirmaID { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual FizickoLice FizickoLice { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbina> Narudzbina { get; set; }
    }
}
