//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sales_systemEntities1 : DbContext
    {
        public sales_systemEntities1()
            : base("name=sales_systemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<FizickoLice> FizickoLice { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<Kupac> Kupac { get; set; }
        public virtual DbSet<Narudzbina> Narudzbina { get; set; }
        public virtual DbSet<NarudzbinaProizvod> NarudzbinaProizvod { get; set; }
        public virtual DbSet<Prodavac> Prodavac { get; set; }
        public virtual DbSet<Proizvod> Proizvod { get; set; }
    }
}
