//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poruka
    {
        public int PorukaID { get; set; }
        public Nullable<int> PosiljalacID { get; set; }
        public Nullable<int> PrimalacID { get; set; }
        public string Sadrzaj { get; set; }
        public System.DateTime DatumSlanja { get; set; }
        public string PosiljalacIme { get; set; }
        public string PrimalacIme { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Korisnici Korisnici1 { get; set; }
    }
}
